import { useEffect, useMemo, useState } from 'react';
import InventoryService from '../../services/inventory.service';
import UserService from '../../services/user.service';
import VentaService from '../../services/venta.service';

const money = (value) => `S/${Number(value || 0).toFixed(2)}`;

function AdminPOS({ onSaleCreated }) {
  const [clients, setClients] = useState([]); const [variants, setVariants] = useState([]); const [clientId, setClientId] = useState(''); const [variantId, setVariantId] = useState(''); const [cart, setCart] = useState([]); const [method, setMethod] = useState('EFECTIVO'); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { try { const [clientResponse, productResponse] = await Promise.all([UserService.getClientes(), InventoryService.getAllProductos()]); setClients(clientResponse.data || []); setVariants((productResponse.data || []).filter((item) => item.stock > 0)); } catch { setMessage('No se pudieron cargar clientes o productos.'); } };
  useEffect(() => { load(); }, []);
  const add = () => { const variant = variants.find((item) => String(item.id) === variantId); if (!variant) return; setCart((current) => { const existing = current.find((item) => item.id === variant.id); if (existing) return current.map((item) => item.id === variant.id ? { ...item, quantity: Math.min(item.quantity + 1, variant.stock) } : item); return [...current, { ...variant, quantity: 1 }]; }); setVariantId(''); };
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + Number(item.producto.prcio_venta || 0) * item.quantity, 0), [cart]); const igv = subtotal * 0.18; const total = subtotal + igv;
  const checkout = async () => { if (!clientId || !cart.length) { setMessage('Selecciona un cliente y agrega al menos un producto.'); return; } setSaving(true); try { await VentaService.crearVenta({ usuarioId: Number(clientId), metodoPago: method, subtotal, costoEnvio: 0, igv, total, items: cart.map((item) => ({ detalleProductoId: item.id, cantidad: item.quantity, precioUnitario: Number(item.producto.prcio_venta) })) }); setCart([]); setMessage('Venta registrada. La factura ya está disponible.'); await load(); if (onSaleCreated) onSaleCreated(); } catch (error) { setMessage(error.response?.data?.message || 'No se pudo registrar la venta.'); } finally { setSaving(false); } };
  return <section className="admin-module"><header className="module-header"><div><p>PUNTO DE VENTA</p><h1>Nueva venta</h1></div></header>{message && <div className="admin-notice" role="status">{message}</div>}<div className="pos-workspace"><section className="pos-selection data-card"><div className="field-grid"><label className="full-field">Cliente<select value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="">Seleccionar cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.nombre} {client.apellido} · {client.dni || client.correo}</option>)}</select></label><label className="full-field">Producto / talla<select value={variantId} onChange={(event) => setVariantId(event.target.value)}><option value="">Seleccionar producto</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.producto.nombre} · Talla {variant.talla} · {variant.marca?.nombre} · Stock {variant.stock}</option>)}</select></label></div><button className="primary-button" onClick={add} disabled={!variantId}>Agregar al carrito</button><p className="helper-text">Si no aparece un cliente, créalo primero en Clientes. Si no aparecen productos, registra marca, categoría y talla en Inventario.</p></section><aside className="sale-summary"><header><p>VENTA ACTUAL</p><h2>Carrito</h2></header>{cart.length === 0 ? <div className="empty-cart">El carrito está vacío</div> : <ul>{cart.map((item) => <li key={item.id}><span><strong>{item.producto.nombre}</strong><small>Talla {item.talla} · {item.marca?.nombre}</small></span><div className="quantity-control"><button onClick={() => setCart(cart.map((row) => row.id === item.id ? { ...row, quantity: Math.max(1, row.quantity - 1) } : row))}>−</button><b>{item.quantity}</b><button onClick={() => setCart(cart.map((row) => row.id === item.id ? { ...row, quantity: Math.min(row.stock, row.quantity + 1) } : row))}>+</button></div><strong>{money(item.producto.prcio_venta * item.quantity)}</strong><button className="remove-line" onClick={() => setCart(cart.filter((row) => row.id !== item.id))}>×</button></li>)}</ul>}<dl className="sale-totals"><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div><dt>IGV (18%)</dt><dd>{money(igv)}</dd></div><div className="grand-total"><dt>Total</dt><dd>{money(total)}</dd></div></dl><label>Método de pago<select value={method} onChange={(event) => setMethod(event.target.value)}><option>EFECTIVO</option><option>TARJETA</option><option>YAPE/PLIN</option></select></label><button className="primary-button full-button" disabled={saving || !cart.length || !clientId} onClick={checkout}>{saving ? 'Registrando…' : 'Finalizar venta'}</button></aside></div></section>;
}

export default AdminPOS;
