import { useEffect, useMemo, useState } from 'react';
import InventoryService from '../../services/inventory.service';
import UserService from '../../services/user.service';
import VentaService from '../../services/venta.service';

const money = (value) => `S/${Number(value || 0).toFixed(2)}`;

function DashboardOverview({ onNavigate }) {
  const [data, setData] = useState({ sales: [], clients: [], variants: [] }); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([VentaService.getAllVentas(), UserService.getClientes(), InventoryService.getAllProductos()]).then(([sales, clients, variants]) => setData({ sales: sales.data || [], clients: clients.data || [], variants: variants.data || [] })).finally(() => setLoading(false)); }, []);
  const revenue = data.sales.reduce((sum, sale) => sum + Number(sale.total || 0), 0); const stock = data.variants.reduce((sum, variant) => sum + Number(variant.stock || 0), 0); const lowStock = data.variants.filter((variant) => variant.stock <= 5); const recent = useMemo(() => data.sales.slice(0, 5), [data.sales]);
  return <section className="admin-module"><header className="module-header"><div><p>RESUMEN EN TIEMPO REAL</p><h1>Dashboard</h1></div><button className="primary-button" onClick={() => onNavigate('pos')}>+ Nueva venta</button></header>{loading ? <div className="empty-state">Cargando indicadores…</div> : <><div className="dashboard-metrics"><article><span>Ingresos</span><strong>{money(revenue)}</strong><small>{data.sales.length} ventas registradas</small></article><article><span>Clientes</span><strong>{data.clients.length}</strong><small>Guardados en MySQL</small></article><article><span>Stock disponible</span><strong>{stock}</strong><small>{data.variants.length} variantes</small></article><article className={lowStock.length ? 'warning-metric' : ''}><span>Stock bajo</span><strong>{lowStock.length}</strong><small>Variantes con 5 o menos</small></article></div><div className="dashboard-content"><div className="data-card"><header className="card-heading"><h2>Ventas recientes</h2><button className="text-button" onClick={() => onNavigate('facturacion')}>Ver facturas</button></header>{recent.length === 0 ? <div className="empty-state"><strong>Aún no hay ventas</strong><span>Registra la primera desde el POS.</span></div> : <table className="admin-table"><thead><tr><th>Venta</th><th>Cliente</th><th>Fecha</th><th>Total</th></tr></thead><tbody>{recent.map((sale) => <tr key={sale.id}><td>F-{String(sale.id).padStart(5, '0')}</td><td>{sale.usuario?.nombre} {sale.usuario?.apellido}</td><td>{new Date(sale.fecha).toLocaleDateString('es-PE')}</td><td><strong>{money(sale.total)}</strong></td></tr>)}</tbody></table>}</div><div className="data-card"><header className="card-heading"><h2>Atención de inventario</h2><button className="text-button" onClick={() => onNavigate('inventario')}>Gestionar</button></header>{lowStock.length === 0 ? <div className="empty-state"><strong>Sin alertas</strong><span>El stock está saludable.</span></div> : <ul className="alert-list">{lowStock.slice(0, 6).map((variant) => <li key={variant.id}><span><strong>{variant.producto.nombre}</strong><small>Talla {variant.talla}</small></span><b>{variant.stock} u.</b></li>)}</ul>}</div></div></>}</section>;
}

export default DashboardOverview;
